noinst_HEADERS = address.h attack.h metrics.h sandbox.h simclist.h
noinst_LIBRARIES = libmetrics.a libsandbox.a libservice_names.a libsimclist.a

libmetrics_a_SOURCES = metrics.c metrics.h
libsandbox_a_SOURCES = sandbox.c sandbox.h
libservice_names_a_SOURCES = address.h attack.h service_names.c
libsimclist_a_SOURCES = simclist.c simclist.h
